# Generated by Django 5.0.7 on 2024-08-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
